version: '3.5'
services:
  nestjs:
    restart: always
    image: nickboomboomboom/doc-api:latest
    env_file:
      - .env # 从宿主机的 .env 文件读取环境变量
    volumes:
      - /home/wuchong/projects/doc-manager/api-data:/app # 将 NestJS 应用程序的数据挂载到宿主机
 
  ui: 
    restart: always
    image: nickboomboomboom/doc:latest
    ports:
      - 22222:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
