name: Docker Image CI

on:
  push:
    branches:
      - main

jobs:
  build-api:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_EMAIL }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          
      - name: Build and push API image
        run: |
          cd api
          docker build . -t nickboomboomboom/doc-api:latest
          docker push nickboomboomboom/doc-api:latest

  build-ui:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_EMAIL }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
      - name: Build and push UI image
        run: |
          cd ui
          docker build . -t nickboomboomboom/doc:latest
          docker push nickboomboomboom/doc:latest

  deploy:
    runs-on: ubuntu-latest
    steps:
        - name: deploy to server 
          env: 
              SSH_PRAVITE_KEY: ${{secrets.SSH_PRAVITE_KEY}}
              SSH_HOST: ${{secrets.SSH_HOST}}
              SSH_USERNAME: ${{secrets.SSH_USERNAME}}
              SSH_PORT: ${{secrets.SSH_PORT}}
          run: |
              echo "$SSH_PRAVITE_KEY" > ssh_key
              chmod 600 ssh_key
              ssh -o StrictHostKeyChecking=no -i ssh_key -p $SSH_PORT $SSH_USERNAME@$SSH_HOST "cd /home/wuchong/projects/doc-manager;docker-compose pull;docker-compose up -d"
              